"""
Author: Srayan Gangopadhyay
2020-08-06
met.no symbol names mapped to emoji
"""


symbols = {
    'fog': '🌫',
    'heavyrain': '🌧',
    'heavyrainandthunder': '⛈',
    'heavyrainshowers_day': '🌧',
    'heavyrainshowers_night': '🌧',
    'heavyrainshowers_polartwilight': '🌧',
    'heavyrainshowersandthunder_day': '⛈',
    'heavyrainshowersandthunder_night': '⛈',
    'heavyrainshowersandthunder_polartwilight': '⛈',
    'heavysleet': '🌨',
    'heavysleetandthunder': '🌨',
    'heavysleetshowers_day': '🌨',
    'heavysleetshowers_night': '🌨',
    'heavysleetshowers_polartwilight': '🌨',
    'heavysleetshowersandthunder_day': '🌨',
    'heavysleetshowersandthunder_night': '🌨',
    'heavysleetshowersandthunder_polartwilight': '🌨',
    'heavysnow': '🌨',
    'heavysnowandthunder': '🌨',
    'heavysnowshowers_day': '🌨',
    'heavysnowshowers_night': '🌨',
    'heavysnowshowers_polartwilight': '🌨',
    'heavysnowshowersandthunder_day': '🌨',
    'heavysnowshowersandthunder_night': '🌨',
    'heavysnowshowersandthunder_polartwilight': '🌨',
    'lightrain': '☔',
    'lightrainandthunder': '⛈',
    'lightrainshowers_day': '☔',
    'lightrainshowers_night': '☔',
    'lightrainshowers_polartwilight': '☔',
    'lightrainshowersandthunder_day': '⛈',
    'lightrainshowersandthunder_night': '⛈',
    'lightrainshowersandthunder_polartwilight': '⛈',
    'lightsleet': '❄',
    'lightsleetandthunder': '⛈',
    'lightsleetshowers_day': '❄',
    'lightsleetshowers_night': '❄',
    'lightsleetshowers_polartwilight': '❄',
    'lightsnow': '🌨',
    'lightsnowandthunder': '⛈',
    'lightsnowshowers_day': '🌨',
    'lightsnowshowers_night': '🌨',
    'lightsnowshowers_polartwilight': '🌨',
    'lightssleetshowersandthunder_day': '⛈',
    'lightssleetshowersandthunder_night': '⛈',
    'lightssleetshowersandthunder_polartwilight': '⛈',
    'lightssnowshowersandthunder_day': '⛈',
    'lightssnowshowersandthunder_night': '⛈',
    'lightssnowshowersandthunder_polartwilight': '⛈',
    'partlycloudy_day': '🌤',
    'partlycloudy_night': '⛅',
    'partlycloudy_polartwilight': '⛅',
    'rain': '🌧',
    'rainandthunder': '⛈',
    'rainshowers_day': '🌧',
    'rainshowers_night': '🌧',
    'rainshowers_polartwilight': '🌧',
    'rainshowersandthunder_day': '⛈',
    'rainshowersandthunder_night': '⛈',
    'rainshowersandthunder_polartwilight': '⛈',
    'sleet': '🌨',
    'sleetandthunder': '⛈',
    'sleetshowers_day': '🌨',
    'sleetshowers_night': '🌨',
    'sleetshowers_polartwilight': '🌨',
    'sleetshowersandthunder_day': '⛈',
    'sleetshowersandthunder_night': '⛈',
    'sleetshowersandthunder_polartwilight': '⛈',
    'snow': '🌨',
    'snowandthunder': '⛈',
    'snowshowers_day': '🌨',
    'snowshowers_night': '🌨',
    'snowshowers_polartwilight': '🌨',
    'snowshowersandthunder_day': '⛈',
    'snowshowersandthunder_night': '⛈',
    'snowshowersandthunder_polartwilight': '⛈',
    'clearsky_day': '🌞',
    'clearsky_night': '🌒',
    'clearsky_polartwilight': '🌆',
    'cloudy': '☁',
    'fair_day': '🌞',
    'fair_night': '🌒',
    'fair_polartwilight': '🌆'
}
